[features]
seeds = true
skip-lint = false
[programs.localnet]
exchange = "HndsTUfB2AZbQifHN9WdKMMQqXghGVwmak2gy3oyzwqV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/athar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
